name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: ./
        with:
          file-names: '["package.json", "READMD.md"]'
          github-token: ${{ secrets.NEW_GITHUB_ACTIONS_TOKEN }}
