name: 'Commit Message Check'
on:
  
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          pwd
          cat $HOME/gitcommitactions/gitcommitactions/index.js
          cat $HOME/gitcommitactions/gitcommitactions/word.txt
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
