name: 'Commit Message Check'
on:
  
  push:
    branches:
      - main
env: 
  instance_running: "running"
  instance_stopped: "stopped"
jobs:
  function:
    runs-on: ubuntu-latest
    outputs: 
          run_UI_jobs: ${{ steps.frontend.outputs.ui}}
          run_services_jobs: ${{ steps.Backend.outputs.backend }}
          container : ${{ steps.Backend.outputs.featureman }} 
                ${{ steps.Backend.outputs.entityman }} 
                ${{ steps.Backend.outputs.flowman }} 
                ${{ steps.Backend.outputs.microflowman }} 
                ${{ steps.Backend.outputs.menubuilderman }}
                ${{ steps.Backend.outputs.screeman }} 
                ${{ steps.Backend.outputs.securityman }} 
                ${{ steps.Backend.outputs.camundasvc }} 
                ${{ steps.Backend.outputs.Auth }}
                ${{ steps.Backend.outputs.templateman }} 
                ${{ steps.Backend.outputs.api }} 
                ${{ steps.Backend.outputs.projectman }} 
                ${{ steps.Backend.outputs.deleteman }}
                ${{ steps.Backend.outputs.githubman }} 
                ${{ steps.Backend.outputs.screengenman }} 
                ${{ steps.Backend.outputs.mongogenman }}
                ${{ steps.Backend.outputs.admingenman }}
                ${{ steps.Backend.outputs.nodegenman }}
                ${{ steps.Backend.outputs.datastoreman }} 
                ${{ steps.Backend.outputs.inframan }} 
                ${{ steps.Backend.outputs.generationman }} 
                ${{ steps.Backend.outputs.frontgenman }}
                ${{ steps.Backend.outputs.backendgenman }} 
                ${{ steps.Backend.outputs.angulargenman }} 
                ${{ steps.Backend.outputs.angtemplateman }} 
                ${{ steps.Backend.outputs.reactgenman }}
                ${{ steps.Backend.outputs.configman }} 
                ${{ steps.Backend.outputs.authgenman }}
                ${{ steps.Backend.outputs.codegenman }} 
                ${{ steps.Backend.outputs.ionicman }} 
                ${{ steps.Backend.outputs.swaggergenman }} 
    steps:
      - uses: actions/checkout@v2
      - name: Check for changes
        id: diff
        run: |
          if [ $GITHUB_BASE_REF ]; then
            git fetch origin $GITHUB_BASE_REF --depth=1
            export FILE_DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            git fetch origin ${{ github.event.before }} --depth=1
            export FILE_DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$FILE_DIFF"
          echo "::set-output name=diff::$( echo "$FILE_DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
      - name: UI to build function
        id: frontend
        run: |
          FILE_DIFF="${{ steps.diff.outputs.diff }}"
          while read path;
          do
            directory="$( echo $path )"
            if [[ $directory != application/clients/desktop/* ]]; then
              echo "::set-output name=ui::notcommited" 
              continue
            else
              echo "::set-output name=ui::commited"
              break
            fi
          done <<< "$FILE_DIFF"
      - name: Services function to build
        if: env.instance_running == 'running'
        id: Backend
        run: |
          FILE_DIFF="${{ steps.diff.outputs.diff }}"
          while read path;
          do
            directory="$( echo $path )"
            if [[ $directory == application/services/featuremanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=featureman::featuremanager"
              continue
            elif [[ $directory == application/services/entitymanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=entityman::entitymanager"
              continue
            elif [[ $directory == application/services/flowmanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=flowman::flowmanager"
              continue
            elif [[ $directory == application/services/microflowmanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=microflowman::microflowmanager"
              continue
            elif [[ $directory == application/services/menubuildermanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=menubuilderman::menubuildermanager"
              continue
            elif [[ $directory == application/services/screenmanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=screenman::screenmanager"
              continue
            elif [[ $directory == application/services/securitymanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=securityman::securitymanager"
              continue
            elif [[ $directory == application/services/Camunda/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=camundasvc::camundasvc"
              continue
            elif [[ $directory == application/services/Auth-Proxy/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=Auth::authproxy"
              continue
            elif [[ $directory == application/services/templatemanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=templateman::templatemanager"
              continue
            elif [[ $directory == application/services/apigateway/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=api::apigateway" 
              continue
            elif [[ $directory == application/services/projectmanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=projectman::projectmanager"
              continue
            elif [[ $directory == application/services/deletemanager/* ]]; then
              echo "::set-output name=backend::commited" 
              echo "::set-output name=deleteman::deletemanager"
              continue
            elif [[ $directory == generator/services/github-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=githubman::githubmanager" 
              continue
            elif [[ $directory == generator/services/screen-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=screengenman::angulargenmanager" 
              continue
            elif [[ $directory == generator/services/mongo-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=mongogenman::mongogenmanager" 
              continue
            elif [[ $directory == generator/services/Admin-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=admingenman::admingenmanger" 
              continue
            elif [[ $directory == generator/services/node-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=nodegenman::nodegenmanager" 
              continue
            elif [[ $directory == generator/services/datastore-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=datastoreman::datastoremanager" 
              continue
            elif [[ $directory == generator/services/infrastructure-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=inframan::inframanager" 
              continue
            elif [[ $directory == generator/services/generation-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=generationman::generationmanager" 
              continue
            elif [[ $directory == generator/services/frontend-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=frontgenman::frontgenmanager" 
              continue
            elif [[ $directory == generator/services/backend-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=backendgenman::backendgenmanager" 
              continue
            elif [[ $directory == generator/services/angular-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=angulargenman::angulargenmanager" 
              continue
            elif [[ $directory == generator/services/angular-template-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=angtemplateman::angtemplatemanager" 
              continue
            elif [[ $directory == generator/services/reactv16-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=reactgenman::reactgenmanager" 
              continue
            elif [[ $directory == generator/services/configurationmanager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=configman::configmanager" 
              continue
            elif [[ $directory == generator/services/auth-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=authgenman::authgenmanager" 
              continue
            elif [[ $directory == generator/services/code-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=codegenman::codegenmanager" 
              continue
            elif [[ $directory == generator/services/ionic-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=ionicman::ionicmanager" 
              continue
            elif [[ $directory == generator/services/swagger-gen-manager/* ]]; then
              echo "::set-output name=backend::commited"
              echo "::set-output name=swaggergenman::swaggergenmanager" 
              continue
            else
              echo "::set-output name=backend::notcommited"
            fi
          done <<< "$FILE_DIFF"
      # - uses: actions/checkout@v2
      # - uses: EndBug/add-and-commit@v6
      #   with: 
      #     path: './generator/services/configurationmanager/src/assests/'
      #     message: 'Add the version and date'
      #     add: '*.json --force'
      #     cwd: './generator/services/configurationmanager/src/assests/'  
      #     token: ${{ secrets.TOKEN }}
      # - run: |
      #     echo "`jq '.base_config[0].value="Alpha-20"' configuration.json`" > ./generator/services/configurationmanager/src/assests/configuration.json
      #     echo "`jq '.base_config[1].value="1.2.14"' configuration.json`" > ./generator/services/configurationmanager/src/assests/configuration.json
      #     echo "`jq '.base_config[2].value="28/12/2020"' configuration.json`" > ./generator/services/configurationmanager/src/assests/configuration.json
          
  UIfrontend:
    name: UIfrontend
    needs: [function]
    if: needs.function.outputs.run_UI_jobs == 'commited'
    runs-on: ubuntu-latest
    steps:
      - name: the rest jobs
        run: echo ${{ needs.function.outputs.run_UI_jobs }}
  services:
    name: Services
    needs: [function]
    if: needs.function.outputs.run_services_jobs == 'commited'
    runs-on: ubuntu-latest
    steps:
      - name: the rest jobs
        run: |
          echo "docker-compose down"
          echo "docker rm -f ${{ needs.function.outputs.container }}"
          echo "docker rmi ${{ needs.function.outputs.container }}"
          echo "docker-compose up -d"
           