name: Test action

on:
  pull_request:
    branches: 
      - master

jobs:
  test_action:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get the latest commit on PR
        id: get-latest-commit
        uses: ./

      - name: print the info of the latest commit
        shell: bash
        run: |
          echo "The latest_commit_message:"
          echo "${{ steps.get-latest-commit.outputs.latest_commit_message }}"
          echo "The latest_commit_sha:"
          echo "${{ steps.get-latest-commit.outputs.latest_commit_sha }}"
          echo "The latest_commit_context:"
          echo "${{ steps.get-latest-commit.outputs.latest_commit_context }}"
      - name: print the latest_commit_context
        run: cat ${{ steps.get-latest-commit.outputs.latest_commit_context }}
