name: 'Commit Message Check'
on:
  
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:      
      - name: Get the latest commit on PR
        id: get-latest-commit
        uses: ActionsRML/get-PR-latest-commit@master

      - name: print the info of the latest commit
        run: |
          echo "The commit message:"
          echo "${{ steps.get-latest-commit.outputs.latest_commit_message }}"
          
          echo "The commit sha:"
          echo "${{ steps.get-latest-commit.outputs.latest_commit_sha }}"
          
          echo "The commit context:"
          cat ${{ steps.get-latest-commit.outputs.latest_commit_context }}
